try{

} catch (e) {
    console.log(e)
}